# Generated by Django 3.2.8 on 2021-11-22 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='_Empty_', max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='_Empty_', max_length=25)),
                ('description', models.CharField(default='_Empty_', max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('comments', models.ManyToManyField(to='core.Comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupname', models.CharField(default='_Empty_', max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('post', models.ManyToManyField(to='core.Post')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
