# Generated by Django 3.2.8 on 2021-11-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
