# Generated by Django 3.2.8 on 2021-11-23 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20211122_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='Group',
            field=models.ManyToManyField(to='core.Group'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
