# Generated by Django 3.2.8 on 2021-11-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211123_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
