# Generated by Django 3.2.8 on 2021-11-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211115_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='file',
            field=models.ManyToManyField(to='core.File'),
        ),
    ]
