# Generated by Django 3.2.8 on 2021-11-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211123_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default='_Empty_', max_length=255),
        ),
    ]
