# Generated by Django 3.2.8 on 2021-11-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin',
            new_name='admins',
        ),
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(to='core.Post'),
        ),
    ]
