# Generated by Django 3.2.8 on 2021-11-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_group_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
    ]
