# Generated by Django 3.2.8 on 2021-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_group_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
    ]
