# Generated by Django 3.2.8 on 2021-11-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_groupmgmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmgmt',
            name='group',
            field=models.ManyToManyField(blank=True, to='core.Group'),
        ),
    ]
