# Generated by Django 3.2.8 on 2021-11-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_groupmgmt_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='groupname',
            new_name='name',
        ),
    ]
