# Generated by Django 3.2.8 on 2021-11-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_groupmgmt_grpmgmt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrpMgmt',
        ),
    ]
