# Generated by Django 3.2.8 on 2021-11-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0014_delete_grpmgmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('groups', models.ManyToManyField(blank=True, to='core.Group')),
            ],
        ),
    ]
