# Generated by Django 3.2.8 on 2021-12-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_usergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='groups',
            new_name='group',
        ),
    ]
