# Generated by Django 3.2.8 on 2021-11-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupname', models.CharField(default='First', max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
