# Generated by Django 3.2.8 on 2021-11-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random',
            field=models.CharField(default='random', max_length=50),
        ),
    ]
