# Generated by Django 3.2.8 on 2021-11-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random',
        ),
    ]
